################################################################################
MLI_FILE		= cordova_battery_status.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-battery-status
################################################################################
